#len(),index(),count()
t1= ('pritha','nishant','epshita', 10,55.6)
print(len(t1))
t2=('e','p','s','h','i','t','a',10,55,57.6,'tithi','p','r','i','t','h','a')
print(t2.index('a'))
print(t2.index('a',7))
print(t2.index('t',7,15))
print(t2.index('t'))
print(t2.count('a'))
print(t2.count('t'))